create database INVOICE5;
use INVOICE5;
create user user1@'localhost' identified by 'user1';
create user user2@'localhost' identified by 'user2';
grant insert,select on INVOICE5.customer to user1 @'localhost';
show grants for user1 @'localhost';
grant update,delete on INVOICE5.* to user2 @'localhost';
show grants for user2 @'localhost';
revoke delete on INVOICE5.* from user2 @'localhost';
create database SCHOOL1;
create database SCHOOL;
use SCHOOL1;
create table student(id int primary key auto_increment,student_name varchar(20),department varchar(30));
desc student;
insert into student values(1,"Abhlash","MCA");
insert into student values(2,"Nayana","MCA");
insert into student values(3,"Anu","MCA");
insert into student values(4,"Ammu","MBA");
commit;
select * from student;
insert into student values(5,"Anju","BCA");
rollback;
select * from student;
insert into student values(6,"Deepak","BCA");
savepoint t1;
insert into student values(8,"Varun","BCA");
rollback to t1;
