create database INVOICE;
use INVOICE;
create table CUSTOMER (cust_id int primary key auto_increment, address varchar(30), city varchar(20), ph_no int);
create table PRODUCT (p_id int primary key auto_increment, pname varchar(20), price int default '0');
create table INVOICE_MASTER (inv_id int primary key auto_increment, cust_id int,constraint cust_id foreign key(cust_id) references CUSTOMER(cust_id),inv_date date);
create table INVOICE_ITEM (inv_id int, constraint inv_id foreign key(inv_id) references INVOICE_MASTER(inv_id),p_id int, constraint p_id foreign key(p_id) references PRODUCT(p_id),quantity int);
desc CUSTOMER;
desc PRODUCT;
desc INVOICE_MASTER;
desc INVOICE_ITEM; 
insert into CUSTOMER values(101,"thoppil house","Kottayam",456768786);
insert into CUSTOMER values(102,"mleveettyl","Pathanamthitta",755374574);
insert into CUSTOMER values(103,"charivukalayil","Ranni",57657898);
insert into CUSTOMER values(104,"thottakuzhi","Ranni",9048385156);
insert into CUSTOMER values(105,"thoppil","konni",456768786);
desc CUSTOMER;
select * from CUSTOMER;
insert into PRODUCT value(200,"Soap",50);
insert into PRODUCT value(205,"Rice",500);
insert into PRODUCT value(206,"Bag",750);
insert into PRODUCT value(209,"Book",50);
insert into PRODUCT value(212,"Pen",10);
select * from PRODUCT;
